import './globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { twMerge } from 'tailwind-merge'

import ResponseDialog from '@/components/ui/dialogs/ResponseDialog'
import { ResponseDialogProvider } from '@/contexts/ResponseDialogContext'

const roboto = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'OddScout',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={twMerge('antialiased', roboto.variable)}>
        <ResponseDialogProvider>
          {children}
          <ResponseDialog />
        </ResponseDialogProvider>
      </body>
    </html>
  )
}
