import './globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { twMerge } from 'tailwind-merge'

import Providers from '@/components/Providers'
import ResponseDialog from '@/components/ui/dialogs/ResponseDialog'
import { Toaster } from '@/components/ui/shadcn/toaster'

const roboto = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'OddScout',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={twMerge(
          'max-h-screen overflow-auto antialiased',
          roboto.variable,
        )}
      >
        <Providers>
          {children}

          <Toaster />
          <ResponseDialog />
        </Providers>
      </body>
    </html>
  )
}
